name: Generate weekly blog post

on:
  schedule:
    - cron: "0 14 * * 1"   # Every Monday 14:00 UTC
  workflow_dispatch:        # Allow manual run

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate post
        run: python scripts/generate_post.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/*.html sitemap.xml
          git commit -m "Auto-generate blog post $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
