name: Generate weekly blog post
on:
  schedule:
    - cron: "0 14 * * 1"   # Mondays 14:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python scripts/generate_post.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/*.html blog/index.html sitemap.xml || true
          git commit -m "Auto-generate blog post $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
