name: Inject GA into all HTML
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run injector
        run: python scripts/inject_ga.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.html blog/*.html || true
          git commit -m "chore: inject GA snippet sitewide" || echo "No changes"
          git push
